-- MySQL Script generated by MySQL Workbench
-- Thu Feb 11 15:21:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nomeCurso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professores` (
  `IdProfessor` INT NOT NULL AUTO_INCREMENT,
  `nomeProfessor` VARCHAR(45) NOT NULL,
  `Cursos_ID` INT NOT NULL,
  PRIMARY KEY (`IdProfessor`, `Cursos_ID`),
  UNIQUE INDEX `IdProfessor_UNIQUE` (`IdProfessor` ASC) VISIBLE,
  INDEX `fk_Professores_Cursos_idx` (`Cursos_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Professores_Cursos`
    FOREIGN KEY (`Cursos_ID`)
    REFERENCES `mydb`.`Cursos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos` (
  `idAlunos` INT NOT NULL AUTO_INCREMENT,
  `nomeAlunos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlunos`),
  UNIQUE INDEX `idAlunos_UNIQUE` (`idAlunos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos_has_Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos_has_Alunos` (
  `Cursos_ID` INT NOT NULL,
  `Alunos_idAlunos` INT NOT NULL,
  PRIMARY KEY (`Cursos_ID`, `Alunos_idAlunos`),
  INDEX `fk_Cursos_has_Alunos_Alunos1_idx` (`Alunos_idAlunos` ASC) VISIBLE,
  INDEX `fk_Cursos_has_Alunos_Cursos1_idx` (`Cursos_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_has_Alunos_Cursos1`
    FOREIGN KEY (`Cursos_ID`)
    REFERENCES `mydb`.`Cursos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_has_Alunos_Alunos1`
    FOREIGN KEY (`Alunos_idAlunos`)
    REFERENCES `mydb`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
